### ISSUE TITLE
1.14.0 iOS app release checklist issue

### ISSUE THREAD

**Issue by 3257** [bubval/waffle-clone#11]
# Summary
v 1.14.0 iOS app release checklist issue.

Main goals:
- Implement google text-to-speech service with the option to choose voices and persistence.
- Implement new design which replaces the old podcast player but still works with the current WNAudioPlayerManager that we have.

**Created wnpodcastplayer project which will include the new podcast player and most of the new UI - repo currently here https://bitbucket.org/tumba/wnpodcastplayer/src/master/**

Implemented so far:
- [x] New podcast player and UI - buttons, slider, scrolling title and relevant delegate functions for interacting with the podcast player.
- [x] Table view listing items to be player UI - table view added and custom self-sizing cell.
- [x] Podcast player view controller with description labels UI - panning up and down works with the playlist button moving the VC to the top, settings button leads to the SettingsVC where voice options are listed and synced with User Defaults.
- [x] Settings View controller following the UI and synced with User Defaults.
- [x] Needed animations created - the loading animation when play button is tapped is created too but it is not hooked up.

- [x] Current TTS demo works with the **feature/tts-demoable** branch - new property added for **audio** for the created audio url in the core data model

To Implement:
- [x] Podcast VC inherits BottomSheetVC which implements pan and etc. - switch that to BottomSheetVC view embedding PodcastVC view but **need to account for the playlist tableView and how that interacts with the BottomSheetVC(might end up as an overkill).**
- [x] Update fonts and colours everywhere needed according to design.
- [x] Replace **WNAudioPlaybackView** player with the new **PodcastPlayerView** together with the rest of the new UI within the **ios-whatsnews project**.
- [x] The old  **WNAudioPlaybackView** player works with the **WNAudioPlaybackManager** class to update the played audio and etc. Keep the **WNAudioPlaybackManager** and align it to work with the new **PodcastPlayerView**.
- [x] Implement logics that feeds all the playlist items to be played in the playlist table view.

- [x] UI - Playlist item current played time and total time shown as **x.xx** instead of as **x : xx**  for the new podcast player - fix that.

- [x] Implement logics for selection and persistence of chosen Voices from Settings VC.
- [x] Update slider's scrubber following design
- [x] Reduce space between slider timeline and duration labels
- [x] Tapping on handle should show the full player
- [x] Disable background scroll and add darker background when audio podcast is visible
- [x] Update margins when per Scott's remarks 

- [x] Add protocol for SettingsVC UserDefaults and implement it within main project
- [x] Add duration to podcast core data model
- [x] Use SettingsVC chosen voices to play correctly-voiced playlist items

- [ ] Settings VC is not following UI design perfectly. Align it when design provided.
- [ ] Track player current item error for **no internet connection** and for **incorrect url** and use it to track playbackStatus .failed and .loading properly 
- [ ] **Implement logics for persistence of downloaded playlist items**.
- [ ] Add lighter top border for contrast to the audio button sheet
- [x] Update background to dark blur with 0.45 grey color for background
- [ ] Remove bottom black bar in newsfeed and article view ??
- [x] Line-height on titles - check against design 
- [ ] Track Audio when app in background
- [x] Add tap to ‘Up Next’ story
- [ ] Floating audio button should be available everywhere
- [x] Do not animate floating audio button when not playing
